sudo: false
language: go
go:
  - 1.7
  - master

install:
  - go get golang.org/x/net/publicsuffix
  - go get github.com/golang/groupcache/lru
  - go get github.com/pkg/profile
  - go get github.com/cloudflare/cfssl/log
  - go get github.com/cloudflare/cfssl/revoke
  - go get github.com/google/certificate-transparency/go
notifications:
  email:
    recipients:
    - paul.vanbrouwershaven@globalsign.com
    on_success: never
    on_failure: change
